<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-21T15:19:13 IST" name="Default suite" finished-at="2025-01-21T15:19:13 IST" duration-ms="241">
    <groups>
    </groups>
    <test started-at="2025-01-21T15:19:13 IST" name="Default test" finished-at="2025-01-21T15:19:13 IST" duration-ms="241">
      <class name="TestNgAssertions.Multipletestcases">
        <test-method signature="Testmethod1()[pri:0, instance:TestNgAssertions.Multipletestcases@6574a52c]" started-at="2025-01-21T15:19:13 IST" name="Testmethod1" finished-at="2025-01-21T15:19:13 IST" duration-ms="23" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testmethod1 -->
        <test-method signature="Testmethod2()[pri:0, instance:TestNgAssertions.Multipletestcases@6574a52c]" started-at="2025-01-21T15:19:13 IST" name="Testmethod2" finished-at="2025-01-21T15:19:13 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testmethod2 -->
        <test-method signature="Testmethod3()[pri:0, instance:TestNgAssertions.Multipletestcases@6574a52c]" started-at="2025-01-21T15:19:13 IST" name="Testmethod3" finished-at="2025-01-21T15:19:13 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testmethod3 -->
        <test-method signature="CollectioAssertion()[pri:0, instance:TestNgAssertions.Multipletestcases@6574a52c]" started-at="2025-01-21T15:19:13 IST" name="CollectioAssertion" finished-at="2025-01-21T15:19:13 IST" depends-on-methods="TestNgAssertions.Multipletestcases.Testmethod1, TestNgAssertions.Multipletestcases.Testmethod2, TestNgAssertions.Multipletestcases.Testmethod3" duration-ms="0" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
TestMethod 2 : Firstassertion failed expected [hello] but found [Hello],
TestMethod 2 : Firstassertion failed expected [hello] but found [Hello],
TestMethod 3 : Second assertionfailed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
TestMethod 2 : Firstassertion failed expected [hello] but found [Hello],
TestMethod 2 : Firstassertion failed expected [hello] but found [Hello],
TestMethod 3 : Second assertionfailed expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at TestNgAssertions.Multipletestcases.CollectioAssertion(Multipletestcases.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CollectioAssertion -->
      </class> <!-- TestNgAssertions.Multipletestcases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
